eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka1,http://eureka2:2002/eureka2
spring:
  application:
    name: item-service
#server:
#  port: 8001
---
spring:
  profiles: item1
server:
  port: 8001
---
spring:
  profiles: item2
server:
  port: 8002