eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
spring:
  application:
    name: order-service
  rabbitmq:
        host: 192.168.180.130
        port: 5672
        username: admin
        password: admin
server:
  port: 8201

